#!/bin/bash
set -euxo pipefail

VAR=$(wc -l < progress)

if [ $VAR = 0 ]; then
    fail-message "You haven't learned about all the classes yet!"
elif [ $VAR == 1 ]; then
    fail-message "You haven't picked a character class yet!"
elif [ $VAR == 2 ]; then
    fail-message "You haven't picked your class weapon(s) yet!"
elif [ $VAR == 3 ]; then
    echo "You successfully created a character!"
fi