#!/bin/bash
apt update && apt upgrade
apt -y install curl

curl -LJO https://raw.githubusercontent.com/wraithxiv/scripts/main/level1.py
chmod +x /root/level1.py

apt install software-properties-common -y

echo '#Temp Alias' >> ~/.bashrc
echo "alias continue='python3 /root/level1.py'" >> ~/.bashrc

source ~/.bashrc

touch level1